import LocalizedStrings from 'react-localization';

export default new LocalizedStrings({
    en:{
      month01:"jan",
      month02:"feb",
      month03:"mar",
      month04:"apr",
      month05:"may",
      month06:"jun",
      month07:"jul",
      month08:"aug",
      month09:"sep",
      month10:"oct",
      month11:"nov",
      month12:"dec",
      want_get_weather: "Want to get the weather by",
      yes: "Yes",
      no: "No",
      day1:"Monday",
      day2:"Tuesday",
      day3:"Wednesday",
      day4:"Thursday",
      day5:"Friday",
      day6:"Saturday",
      day0:"Sunday",
    },
    ru: {
      month01:"янв",
      month02:"фев",
      month03:"мар",
      month04:"апр",
      month05:"май",
      month06:"июн",
      month07:"июл",
      month08:"авг",
      month09:"сен",
      month10:"окт",
      month11:"ноя",
      month12:"дек",
      want_get_weather: "Хотите получить погоду по",
      yes: "Да",
      no: "Нет",
      day1:"Понедельник",
      day2:"Вторник",
      day3:"Среда",
      day4:"Четверг",
      day5:"Пятница",
      day6:"Суббота",
      day0:"Воскресенье",
    }
   });